
# Pyro dependencies for Bayesian optimization
# pyro-ppl>=1.9.0
# torch>=2.0.0

# Pyro dependencies for Bayesian optimization
# pyro-ppl>=1.9.0
# torch>=2.0.0

# Pyro dependencies for Bayesian optimization
# pyro-ppl>=1.9.0
# torch>=2.0.0

# Pyro dependencies for Bayesian optimization
# pyro-ppl>=1.9.0
# torch>=2.0.0

# Pyro dependencies for Bayesian optimization
# pyro-ppl>=1.9.0
# torch>=2.0.0

# Pyro dependencies for Bayesian optimization
# pyro-ppl>=1.9.0
# torch>=2.0.0

# Pyro dependencies for Bayesian optimization
# pyro-ppl>=1.9.0
# torch>=2.0.0

# Pyro dependencies for Bayesian optimization
# pyro-ppl>=1.9.0
# torch>=2.0.0
